### PR TITLE
Added Sponsor's logo in Community Partnership

### PR DESCRIPTION
**Pull request by adityaslyf**
Screenshot from 2023-05-31 13-48-43

### CODE REVIEW

**Comment by adityaslyf** [comment]
@Mr-Sunglasses kindly look into this.

**Comment by Mr-Sunglasses** [comment]
@adityaslyf where is carousel?

**Comment by adityaslyf** [comment]
@Mr-Sunglasses check now

**Comment by adityaslyf** [comment]
Screenshot from 2023-05-31 17-37-07

<h1>Aslo added respective links to the Logos </h1>

**Pull request merged**
